<a href="https://colab.research.google.com/github/VikrantKapoor24/Numpy-coreTech/blob/main/Numpy_coreTech.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as na
sp=[5,3,7,0,58]
x=na.array(sp)
print(x)
print(na.array(sp))
									

[ 5  3  7  0 58]
[ 5  3  7  0 58]


In [ ]:
import numpy as na
marks=[ [4,3,5] , [6,4,7] ]
x=na.array(marks)
print(x)
print(x[1])
print(x[1][0])
print(x[1][2])



[[4 3 5]
 [6 4 7]]
[6 4 7]
6
7


In [ ]:
import numpy as np
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print("Array with List  \n", arr)

arr = np.array((1, 3, 2))
print("\nArray using  tuple:\n", arr)

arr=np.array({1:"one", 2:"two"})
print("\n Array using Dictionary ", arr)


Array with List  
 [[1 2 3]
 [4 5 6]]

Array using  tuple:
 [1 3 2]

 Array using Dictionary  {1: 'one', 2: 'two'}


In [ ]:
import numpy as np

arr = np.array([[-1, 2, 0, 4],
                [4, -0.5, 6, 0],
                [2.6, 0, 7, 8],
                [3, -7, 4, 2.0]])
print("Initial Array: ")
print(arr)
sliced_arr = arr[:2, ::2]
print ("Array with first 2 rows and alternate columns(0 and 2):\n", sliced_arr)
Index_arr = arr[[1, 1, 0, 3], 
                [3, 2, 1, 0]]
print ("\nElements at indices (1, 3), (1, 2), (0, 1), (3, 0):\n", Index_arr)


Initial Array: 
[[-1.   2.   0.   4. ]
 [ 4.  -0.5  6.   0. ]
 [ 2.6  0.   7.   8. ]
 [ 3.  -7.   4.   2. ]]
Array with first 2 rows and alternate columns(0 and 2):
 [[-1.  0.]
 [ 4.  6.]]

Elements at indices (1, 3), (1, 2), (0, 1), (3, 0):
 [0. 6. 2. 3.]


In [ ]:
import numpy as np
a = np.array([[1, 2], [3, 4]])

b = np.array([[4, 3],[2, 1]])

print ("Adding 1 to every element:", a + 1)

print ("\nSubtracting 2 from each element:", b - 2)

print ("\nSum of all array elements: ", a.sum())

print ("\nArray sum:\n", a + b)


Adding 1 to every element: [[2 3]
 [4 5]]

Subtracting 2 from each element: [[ 2  1]
 [ 0 -1]]

Sum of all array elements:  10

Array sum:
 [[5 5]
 [5 5]]


In [ ]:
import numpy as nu 
a=nu.array(['Piyush','Priyank','Roshan'])
b=nu.array( [ [456,563,4,5,45],[435,34,53,53,45] ] )
print(a,b)
print(type(a), type(b))
print(a.shape, b.shape)
print(a.itemsize, b.itemsize)

['Piyush' 'Priyank' 'Roshan'] [[456 563   4   5  45]
 [435  34  53  53  45]]
<class 'numpy.ndarray'> <class 'numpy.ndarray'>
(3,) (2, 5)
28 8


In [ ]:

import numpy as np 
als={10000:"a" , 25000:"b", 3:"c",4:"d",5:"e"}
ar3=np.fromiter(als,dtype=np.int32)
print(ar3)
ar4=np.fromiter(als,dtype=np.int64)
print(ar4)
ar5=np.fromiter(als,dtype=np.float32)
print(ar5)



[10000 25000     3     4     5]
[10000 25000     3     4     5]
[1.0e+04 2.5e+04 3.0e+00 4.0e+00 5.0e+00]


In [ ]:

import numpy as np 
als=["a","b","c","d","e"]
atp=(1.5,2.5,3.5,4.5,6.6)
als2=  [ a*2 -3 for a in range(2,6) ] 
print(als2)
als3=  [ a*10 -5 for a in range(5,25,5) ] 
print(als3)


[1, 3, 5, 7]
[45, 95, 145, 195]


In [ ]:

import numpy as np 
astr="This is Piyush"
val=np.fromiter(astr,dtype="U2")
print(val)

['T' 'h' 'i' 's' ' ' 'i' 's' ' ' 'P' 'i' 'y' 'u' 's' 'h']


In [ ]:

import numpy as np 
astr="This is PiyusH"
val=np.fromiter(astr,dtype="U2")
print(val)
print(val[1])
print(val[-1])


['T' 'h' 'i' 's' ' ' 'i' 's' ' ' 'P' 'i' 'y' 'u' 's' 'H']
h
H


In [ ]:
import numpy as np
rat=np.arange(6)
print(rat)

ca=np.arange(5, dtype='float32')
print(ca)

cx=np.linspace(10,20,6)
print(cx)

cxa=np.linspace(15,20,8)
print(cxa)

gr=np.arange(6)
print(gr)
ngr=gr.reshape(2,3)
print(ngr)
mgr=gr.reshape(3,2)
print(mgr)



[0 1 2 3 4 5]
[0. 1. 2. 3. 4.]
[10. 12. 14. 16. 18. 20.]
[15.         15.71428571 16.42857143 17.14285714 17.85714286 18.57142857
 19.28571429 20.        ]
[0 1 2 3 4 5]
[[0 1 2]
 [3 4 5]]
[[0 1]
 [2 3]
 [4 5]]


In [ ]:
import numpy as np 
a=np.arange(6)
print(a)
b=a.reshape(2,3)
print(b)
c=a.reshape(3,2)
print(c)
d=a.reshape(6,1)
print(d)
e=a.reshape(1,6)
print(e)


[0 1 2 3 4 5]
[[0 1 2]
 [3 4 5]]
[[0 1]
 [2 3]
 [4 5]]
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]
[[0 1 2 3 4 5]]


In [ ]:
import numpy as np 
a=np.arange(8)
print(a)
b=a.reshape(2,4)
print(b)
c=a.reshape(4,2)
print(c)
d=a.reshape(8,1)
print(d)
e=a.reshape(1,8)
print(e)


[0 1 2 3 4 5 6 7]
[[0 1 2 3]
 [4 5 6 7]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]]
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]
[[0 1 2 3 4 5 6 7]]


In [ ]:
import numpy as np 
a=np.arange(10.0).reshape(5,2)
print(a)
print(np.arange(12.0).reshape(4,3))



[[0. 1.]
 [2. 3.]
 [4. 5.]
 [6. 7.]
 [8. 9.]]
[[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]
 [ 9. 10. 11.]]


In [ ]:
import numpy as np 
from sys import getsizeof 

a=np.array([ [41,24] , [445,54] ,[125,141]] , dtype='int16')
print(a)
print(getsizeof(a))


[[ 41  24]
 [445  54]
 [125 141]]
124


In [ ]:
import numpy as np 
a=np.empty( [3,2] )
print(a)
b=np.empty( [3,2] , dtype=np.int16 )
print(b)
c=np.empty( [3,2] , dtype=np.int8 )
print(c)
print(a.dtype , b.dtype)

[[0.0e+000 4.9e-324]
 [9.9e-324 1.5e-323]
 [2.0e-323 2.5e-323]]
[[ 41  24]
 [445  54]
 [125 141]]
[[0 1]
 [1 1]
 [1 1]]
float64 int16


In [ ]:
import pandas as pd
ds1 = pd.Series([2, 4, 6, 8, 10])
ds2 = pd.Series([1, 3, 5, 7, 10])
print("Series1:")
print(ds1)
print("Series2:")
print(ds2)
print("Compare the elements of the said Series:")
print("Equals:")
print(ds1 == ds2)
print("Greater than:")
print(ds1 > ds2)
print("Less than:")
print(ds1 < ds2)

Series1:
0     2
1     4
2     6
3     8
4    10
dtype: int64
Series2:
0     1
1     3
2     5
3     7
4    10
dtype: int64
Compare the elements of the said Series:
Equals:
0    False
1    False
2    False
3    False
4     True
dtype: bool
Greater than:
0     True
1     True
2     True
3     True
4    False
dtype: bool
Less than:
0    False
1    False
2    False
3    False
4    False
dtype: bool


In [ ]:
import numpy as np 
a=np.empty( [3,2] )
print(a)
b=np.empty( [3,2] , dtype=np.int16 )
print(b)
c=np.empty( [3,2] , dtype=np.int8 )
print(c)
print(a.dtype , b.dtype)

[[0.0e+000 4.9e-324]
 [9.9e-324 1.5e-323]
 [2.0e-323 2.5e-323]]
[[ 12816 -30779]
 [ 21880      0]
 [     1      0]]
[[0 1]
 [1 1]
 [1 1]]
float64 int16


In [ ]:
import numpy as np 

e=np.zeros( [4,3] )
print(e)
f=np.zeros( [3,4] , dtype=np.int64 ,order='F')
print(f)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [1]:
import numpy as np 
a=np.ones(5)
b=np.ones(5, dtype='int32')

print(a)
print(b)

c=np.ones((2,3))
print(c)

x = np.arange(6)
x = x.reshape((2, 3))
print(x)
print(np.ones_like(x))

[1. 1. 1. 1. 1.]
[1 1 1 1 1]
[[1. 1. 1.]
 [1. 1. 1.]]
[[0 1 2]
 [3 4 5]]
[[1 1 1]
 [1 1 1]]


In [2]:
import numpy as np 

e=np.zeros( [4,2] )
print(e)
f=np.zeros( [1,3] , dtype=np.int64 )

print(f)
y = np.arange(5, dtype=np.int64)
print(y)
z= np.zeros_like(y)
print(z)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
[[0 0 0]]
[0 1 2 3 4]
[0 0 0 0 0]


In [3]:
import numpy as np 
a=np.ones(3,dtype='int64')
b=np.ones(2)
print(a,b)
c=np.ones((3,3))
print(c)
x = np.arange(8)
x1 = x.reshape((2, 4))
print(x1)
print(np.ones_like(x1))

[1 1 1] [1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0 1 2 3]
 [4 5 6 7]]
[[1 1 1 1]
 [1 1 1 1]]


In [4]:
import numpy as np 

e=np.zeros( [4,3] )
print(e)
f=np.zeros( [3,4] , dtype=np.int64 )

print(f)
y = np.arange(3, dtype=float)
print(y)
z= np.zeros_like(y)
print(z)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[0. 1. 2.]
[0. 0. 0.]


In [5]:
import numpy as np 
a= np.full((2, 2), np.inf)
print(a)
b=np.full((2, 2), 10)
print(b)
c=np.full((2, 2), [1, 2])
print(c)


[[inf inf]
 [inf inf]]
[[10 10]
 [10 10]]
[[1 2]
 [1 2]]


In [6]:
import numpy as np 
a= np.full((2, 4), np.inf)
print(a)
b=np.full((2, 2), 10)
print(b)
b1=np.full((2,4),10, dtype=np.int32)
print(b1)
c=np.full((2, 2), [1, 2])
print(c)


[[inf inf inf inf]
 [inf inf inf inf]]
[[10 10]
 [10 10]]
[[10 10 10 10]
 [10 10 10 10]]
[[1 2]
 [1 2]]


In [8]:
import numpy as np 

x = np.arange(6, dtype=int)
a=np.full_like(x, 1)
print(a)
b=np.full_like(x, 0.1)
print(b)
c=np.full_like(x, 0.1, dtype=np.double)
print(c)
d=np.full_like(x, np.nan, dtype=np.double)
print(d)


[1 1 1 1 1 1]
[0 0 0 0 0 0]
[0.1 0.1 0.1 0.1 0.1 0.1]
[nan nan nan nan nan nan]


In [11]:
import numpy as np 
x = np.arange(6, dtype=np.int32)
a=np.full_like(x, 75)
print(a)
b=np.full_like(x, 25)
print(b)
c=np.full_like(x, 10.101, dtype=np.double)
print(c)
d=np.full_like(x, '10.5', dtype=np.double)
print(d)


[75 75 75 75 75 75]
[25 25 25 25 25 25]
[10.101 10.101 10.101 10.101 10.101 10.101]
[10.5 10.5 10.5 10.5 10.5 10.5]


In [12]:
import numpy as np 
x = np.arange(6, dtype=np.int32)
a=np.full_like(x, 75)
print(a)
b=np.full_like(x, 'knp', dtype=np.string_)
print(b)
c=np.full_like(x, 10.101, dtype=np.double)
print(c)
d=np.full_like(x, '10.5', dtype=np.double)
print(d)


[75 75 75 75 75 75]
[b'k' b'k' b'k' b'k' b'k' b'k']
[10.101 10.101 10.101 10.101 10.101 10.101]
[10.5 10.5 10.5 10.5 10.5 10.5]


In [ ]:
import numpy as np 

x = np.array([1, 2, 3])
y = x
z = np.copy(x)

x[0] = 10
x[0] == y[0]
print( x[0] == z[0] )

a = np.array([1, 'm', [2, 3, 4]], dtype=object)
b = np.copy(a)
b[2][0] = 10
print(a)


In [ ]:
import numpy as np 
print( np.eye(3))
print( np.full((3,4),8))
print(np.random.rand(2,7))
print(np.random.rand(2,7)*100)
print(np.random.randint(6, size=(2,7)))



In [ ]:
import numpy as np 
ar=np.array([2,4,6,8,10,12])
print(ar)
print(ar[1])
print(ar[1:])
print(ar[:1])
print(ar[1:4])
print(ar[1:-2])
print(ar[1:7:2])





In [ ]:
import numpy as np 
ar=np.array( [ [2,4,6], [8,10,12] ,[1,3,5]] )
print(ar)
print(ar[1:,2:])
print(ar[1:,0])
print(ar[0,:1])
print(ar[-1 , 1:])
print(ar[1:-2])
print(ar[1:3])
print(ar[::1, ::3])





In [ ]:
import numpy as np 
ar=np.array( [ [2,4,6], [8,10,12] ,[1,3,5] , [11,22,33]] )
print(ar)
print(ar[1:3,2:4])
print(ar[1:3,0:3])
print(ar[0:3,0:1])
print(ar[:: , 1:])
print(ar[1:-2 , ::])
print(ar[1:3 , 3:-1])
print(ar[::2, ::1])





In [ ]:
import numpy as np 
a=[1,3,5]
b=[2,3,6]
c=[ [11,22,33] , [44,55,66]]
d= [  [100] , [200]]
print(a,b,c,d)
x=np.vstack(a,b)
y=np.hstack(b,c)
print(x)
print(y)
z=np.vstack(c,d)
print(z)




In [ ]:

import numpy as np 
x=np.array([ [1,2,3,4,5] , [5,4,3,2,1] ,[6,7,8,9,10] , [10,9,8,7,6] ])

print(x[1:3 , 3:1:-1])
print(x[1:3 , ])
print(x[: , 3:1:-1])


In [ ]:
import numpy as np
f = np.array([1,2,3])
g = np.array([4,5,6])

print('Horizontal Append:', np.hstack((f, g)))
print('Vertical Append:'); print(np.vstack((f, g)))


In [ ]:
print(print('ok'))

ok
None
